export const AUTH_OAUTH_PROVIDERS = 'AUTH_OAUTH_PROVIDERS';
export const AUTH_TOKEN_SERVICE = 'AUTH_TOKEN_SERVICE';
export const AUTH_REFRESH_TOKEN_REPOSITORY = 'AUTH_REFRESH_TOKEN_REPOSITORY';
export const AUTH_USER_IDENTITY = 'AUTH_USER_IDENTITY';
